pool:
  vmImage: ubuntu-latest
stages:
- stage: SASTMABEL
  jobs:
  - job:
    displayName: 'SAST'
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'sonar_final'
        organization: 'finalmabel'
        scannerMode: 'MSBuild'
        projectKey: 'finalmabel_spring-boot-kubernetes'
        projectName: 'spring-boot-kubernetes'

    
